title: Science & Us
url: https://scienceandus.org
description: Science & Us is a youth-led organization helping high schoolers practice communicating STEM (science, technology, engineering, math) topics and learn about careers bridging STEM and society.

global_nav_links:
#  - name: About
#    url: /about

sass:
  style: compressed

permalink: /:title

collections:
  speakers:
    output: true
  team:
    output: false

defaults:
  -
    scope:
      path: ""
    values:
      layout: "base"
  -
    scope:
      path: ""
      type: "speakers"
    values:
      layout: "speaker"