title: Science & Us
url: scienceandus.org
description: Science & Us is a youth-led organization helping high schoolers practice communicating STEM (science, technology, engineering, math) topics and learn about careers bridging STEM and society.

global_nav_links:
#  - name: About
#    url: /about

sass:
  style: compressed

permalink: /:title

collections:
  invited_experts:
    output: true