title: Science & Us
url: https://scienceandus.org # no slash means that all relative URLs that prepend site.url must begin with a slash

# tagline and description for meta tags
tagline: Making the Complex Compelling
description: We're a youth-led organization teaching high school students science communication skills and about careers bridging STEM and society.

permalink: /:title # clean URLs, e.g. /about as opposed to /about.html

global-nav:
  - title: About
    url: /about
  - title: Workshop
    url: /#workshop
  - title: Blog
    url: /blog
  - title: Donate
    url: /donate
  - title: Contact
    url: /contact

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

sass:
  style: compressed