---
title: Science and Us
url: https://scienceandus.org
description:
  We're a student-led nonprofit that runs events and creates online resources
  to help high schoolers learn science communication. Sign up for our Makeathon on
  January 25, 2020, at MIT!

# include preceding slash
logo_path: /assets/logo.png
favicon_path: /assets/favicon.ico
stylesheet_path: /styles/styles.css

twitter_handle: "@scienceandus"

nav_links:
  - url: /about/
    title: About

collections:
  team_members:
    title: Team Members
    output: false
  posts:
    title: Posts
    output: true
  speakers:
    title: Speakers
    output: false
  uploads:
    title: Uploads
    output: true

# set the default layout to `default` for every page
defaults:
  - scope:
      path: ""
    values:
      layout: default

social_links:
  - url: https://www.instagram.com/scienceandus/
    icon_path: "/icons/ig.svg"
    platform_and_username: "Instagram: @scienceandus"
  - url: https://www.facebook.com/sciandus
    icon_path: "/icons/fb.svg"
    platform_and_username: "Facebook: @sciandus"
  - url: https://twitter.com/scienceandus
    icon_path: "/icons/twitter.svg"
    platform_and_username: "Twitter: @scienceandus"

sass:
  style: compressed

include:
  - _redirects

permalink: /:title/
