title: Science & Us
# tagline and description for meta tags
tagline: Making the Complex Compelling
description: We're a youth-led organization teaching high school students about science communication and cross-disciplinary fields that support STEM.
url: //scienceandus.github.io # no slash means that all relative URLs that prepend site.url must begin with a slash

permalink: /:title # clean URLs, e.g. /about as opposed to /about.html

# notes:
# - order of links in this file determines order on website
# - all relative URLs should be appended to site.url, regardless of source file directory

# homepage links
links:
  - name: About
    url: /about
  - name: Event
    url: /#event
  - name: In the Community
    url: /community
  - name: Join
    url: /join

sass:
  style: compressed

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
